### ISSUE TITLE
NameError: name 'data_dir' is not defined

### ISSUE THREAD

**Issue by akankshadash** [alteryx/open_source_demos#44]
![image](https://user-images.githubusercontent.com/61039826/152741120-7af1a33f-73f6-4b1d-a04c-71f54c7a7afc.png)

any suggestion

**Comment by thehomebrewnerd** [comment]
I think you need to remove the `%%timeit` magic command from the cell for this to work.

**Comment by akankshadash** [comment]
> I think you need to remove the `%%timeit` magic command from the cell for this to work.

Yup thanks it's working now but got different error now
