### ISSUE TITLE
ImportError: cannot import name 'infer_feature_types' from 'evalml.utils.gen_utils'

### ISSUE THREAD

**Issue by akankshadash** [alteryx/open_source_demos#47]
Predicting Customer Churn -problem statement trying to run in kaggle

Library -EVALML
Error-ImportError: cannot import name 'infer_feature_types' from 'evalml.utils.gen_utils'

![image](https://user-images.githubusercontent.com/61039826/153134806-e7166117-a709-47da-a99e-0dc687ccab62.png)

**Comment by gsheni** [comment]
@akankshadash As we had mentioned earlier, we are working on updating this notebook with the new EvalML api. Stay tuned:
- https://github.com/alteryx/open_source_demos/pull/29
